version: 2
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          working_directory: ~/project/packages/react-discovery-app
          name: 'build docker image'
          command: |
            echo ${CIRCLE_BRANCH}
            docker build --build-arg CIRCLE_BRANCH=$CIRCLE_BRANCH .

workflows:
  build:
    jobs:
      - build
  version: 2

