services:
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl/certs:/etc/ssl/certs
    networks:
      - discovery-app-net
  discovery-app:
    environment:
      - REACT_APP_SEARCH_APOLLO_SERVER=http://ec2-3-88-32-73.compute-1.amazonaws.com:4000
    image: 177981160483.dkr.ecr.us-east-1.amazonaws.com/christopher-h-johnson/react-discovery:latest
    ports:
      - "3000:3000"
    networks:
      - discovery-app-net
  graphql-iiif:
    image: 177981160483.dkr.ecr.us-east-1.amazonaws.com/christopher-h-johnson/graphql-iiif-server:latest
    ports:
      - "4000:4000"
    networks:
      - discovery-app-net

networks:
  discovery-app-net:

