---
name: "[CI] Run Terragrunt for each environment"

on:
  push:
    branches: ["master"]

jobs:
  ci-dev:
    uses: ./.github/workflows/workflow.yml
    with:
      working-dir: 'deployments/dev'
      apply: ${{ github.ref_name == 'master' }}
      environment: dev
    secrets: inherit
